/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;
import java.util.List;
import javax.swing.DefaultListModel;


/**
 *
 * @author Nouvella Rahma Fitrah Legarsi / 24060124120029
 */
public class JFrameUtama extends javax.swing.JFrame {
    MysqlMahasiswaService service = new MysqlMahasiswaService();
    DefaultListModel dlmID = new DefaultListModel();
    DefaultListModel dlmNama = new DefaultListModel();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUtama.class.getName());

    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
        initComponents();
        jListID.setModel(dlmID);
        jListNama.setModel(dlmNama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonAmbilData = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jTextFieldUpdateID = new javax.swing.JTextField();
        jTextFieldUpdateNama = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jTextFieldDeleteID = new javax.swing.JTextField();
        jTextFieldDeleteNama = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListID = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNama = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Kelola Data Mahasiswa");

        jButtonAmbilData.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonAmbilData.setText("Ambil Semua Data");
        jButtonAmbilData.addActionListener(this::jButtonAmbilDataActionPerformed);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Nama");

        jTextFieldNama.addActionListener(this::jTextFieldNamaActionPerformed);

        jButtonAdd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonAdd.setText("Tambahkan");
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jTextFieldUpdateNama.addActionListener(this::jTextFieldUpdateNamaActionPerformed);

        jButtonUpdate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonUpdate.setText("Edit");
        jButtonUpdate.addActionListener(this::jButtonUpdateActionPerformed);

        jTextFieldDeleteID.addActionListener(this::jTextFieldDeleteIDActionPerformed);

        jTextFieldDeleteNama.addActionListener(this::jTextFieldDeleteNamaActionPerformed);

        jButtonDelete.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonDelete.setText("Hapus");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAdd)
                            .addComponent(jLabel3)
                            .addComponent(jButtonAmbilData)
                            .addComponent(jLabel4))
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addComponent(jTextFieldNama)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldDeleteID, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jTextFieldUpdateID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDeleteNama)
                            .addComponent(jTextFieldUpdateNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAmbilData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUpdateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUpdateNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdate))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDeleteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDeleteNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        jListID.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListIDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListID);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("ID");

        jListNama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListNama);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("NAMA");

        jButtonReset.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonReset.setText("Reset Indeks");
        jButtonReset.addActionListener(this::jButtonResetActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonReset)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonReset)))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAmbilDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmbilDataActionPerformed
        dlmID.clear();
        dlmNama.clear();
        List<Mahasiswa> list = service.getAll();

        for (Mahasiswa mhs : list) {
            dlmID.addElement(mhs.getId());
            dlmNama.addElement(mhs.getNama());
        }
    }//GEN-LAST:event_jButtonAmbilDataActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        Mahasiswa mhs = new Mahasiswa();
        mhs.setNama(jTextFieldNama.getText());
        
        service.add(mhs);
        jTextFieldNama.setText("");
        dlmID.clear();
        dlmNama.clear();

        List<Mahasiswa> list = service.getAll();
        for (Mahasiswa m : list) {

            dlmID.addElement(m.getId());
            dlmNama.addElement(m.getNama());
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldDeleteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDeleteIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDeleteIDActionPerformed

    private void jTextFieldUpdateNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUpdateNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUpdateNamaActionPerformed

    private void jTextFieldDeleteNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDeleteNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDeleteNamaActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        int id = Integer.parseInt(jTextFieldUpdateID.getText());
        String nama = jTextFieldUpdateNama.getText();
        Mahasiswa mhs = new Mahasiswa();
        mhs.setId(id);
        mhs.setNama(nama);
        service.update(mhs);
        dlmID.clear();
        dlmNama.clear();

        List<Mahasiswa> list = service.getAll();
        for (Mahasiswa m : list) {
            dlmID.addElement(m.getId());
            dlmNama.addElement(m.getNama());
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        service.indexReset();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int id = Integer.parseInt(jTextFieldDeleteID.getText());
        service.delete(id);
        dlmID.clear();
        dlmNama.clear();

        List<Mahasiswa> list = service.getAll();
        for (Mahasiswa m : list) {
            dlmID.addElement(m.getId());
            dlmNama.addElement(m.getNama());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jListIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListIDMouseClicked
        int index = jListID.getSelectedIndex();
        Object id = dlmID.getElementAt(index);
        Object nama = dlmNama.getElementAt(index);

        jTextFieldDeleteID.setText(id.toString());
        jTextFieldDeleteNama.setText(nama.toString());
        jTextFieldUpdateID.setText(id.toString());
        jTextFieldUpdateNama.setText(nama.toString());
    }//GEN-LAST:event_jListIDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAmbilData;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jListID;
    private javax.swing.JList<String> jListNama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldDeleteID;
    private javax.swing.JTextField jTextFieldDeleteNama;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldUpdateID;
    private javax.swing.JTextField jTextFieldUpdateNama;
    // End of variables declaration//GEN-END:variables
}
